'use client';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { BarChart3, Boxes, LayoutDashboard, LogOut, Menu, MessageCircle, Package, Settings, Store, Tags, Users, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import NotificationBell from '@/components/admin/NotificationBell';
import BrandMark from '@/components/ui/BrandMark';
const navigation = [['/admin', 'Dashboard', LayoutDashboard], ['/admin/brand', 'Brand', Store], ['/admin/store', 'Store settings', Settings], ['/admin/products', 'Products', Package], ['/admin/categories', 'Categories', Tags], ['/admin/orders', 'Orders', Boxes], ['/admin/leads', 'Leads', MessageCircle], ['/admin/customers', 'Customers', Users], ['/admin/discounts', 'Discounts', Tags], ['/admin/analytics', 'Analytics', BarChart3]] as const;
export default function AdminLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname(); const router = useRouter(); const [name, setName] = useState('Store Admin'); const [menuOpen, setMenuOpen] = useState(false);
  useEffect(() => { fetch('/api/auth/me').then(response => response.ok ? response.json() : null).then(data => data?.user && setName(data.user.name)); }, []);
  const active = (href: string) => href === '/admin' ? pathname === href : pathname.startsWith(href); const current = navigation.find(([href]) => active(href));
  return <div className="dashboard-layout">{menuOpen && <button className="sidebar-overlay" aria-label="Close navigation" onClick={() => setMenuOpen(false)}/>}<aside className={`sidebar ${menuOpen ? 'open' : ''}`}><Link href="/admin" className="sidebar-logo" onClick={() => setMenuOpen(false)}><BrandMark/><span><span className="sidebar-logo-text">ShopSaaS</span><span className="sidebar-logo-sub">Store Admin</span></span><button className="sidebar-close" type="button" onClick={event => { event.preventDefault(); setMenuOpen(false); }}><X size={18}/></button></Link><nav className="sidebar-nav"><div className="sidebar-section-label">Navigation</div>{navigation.map(([href, label, Icon]) => <Link className={`sidebar-item ${active(href) ? 'active' : ''}`} href={href} key={href} onClick={() => setMenuOpen(false)}><Icon size={18}/>{label}</Link>)}</nav><div className="sidebar-footer"><div className="sidebar-user"><span className="avatar">{name[0]?.toUpperCase()}</span><span>{name}<small>Store manager</small></span></div><button className="sidebar-item w-full danger-link" onClick={async () => { await fetch('/api/auth/logout', { method: 'POST' }); router.push('/login'); }}><LogOut size={18}/>Logout</button></div></aside><main className="main-content"><header className="dashboard-header"><button className="mobile-menu-btn" aria-label="Open navigation" onClick={() => setMenuOpen(true)}><Menu size={20}/></button><div><div className="dashboard-header-title">{current?.[1] ?? 'Store Admin'}</div><div className="dashboard-header-sub">Manage your online store</div></div><div className="dashboard-header-right"><NotificationBell/></div></header><div className="page-content">{children}</div></main></div>;
}
