'use client';
import Link from 'next/link'; import { useEffect, useState } from 'react'; import Pagination from '@/components/ui/Pagination';
import { formatMoney } from '@/lib/currency';
import { useAdminStore } from '@/components/admin/useAdminStore';
type Product = { id: string; name: string; price: number; stock: number; status: string; thumbnail: string }; type Category = { id: string; name: string };
export default function ProductsPage() {
  const store = useAdminStore();
  const [items, setItems] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [categoryId, setCategoryId] = useState(''); const [page, setPage] = useState(1); const perPage = 10;
  const load = () => { const query = new URLSearchParams(); if (search) query.set('search', search); if (status) query.set('status', status); if (categoryId) query.set('categoryId', categoryId); return fetch(`/api/admin/products?${query}`).then(response => response.json()).then(data => setItems(data.products ?? [])); };
  useEffect(() => { fetch('/api/admin/categories').then(response => response.json()).then(data => setCategories(data.categories ?? [])); }, []); useEffect(() => { const timer = window.setTimeout(() => { setPage(1); void load(); }, 180); return () => window.clearTimeout(timer); }, [search, status, categoryId]);
  const pageCount = Math.ceil(items.length / perPage); const visible = items.slice((page - 1) * perPage, page * perPage);
  return <><div className="page-header"><div><h1 className="page-title">Products</h1><p className="page-subtitle">Create and manage {store?.name??'this store'}&apos;s private catalogue.</p></div><Link href="/admin/products/new" className="btn btn-primary">Add product</Link></div><div className="filter-bar"><input className="form-input" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search products"/><select className="form-select" value={status} onChange={event => setStatus(event.target.value)}><option value="">All statuses</option><option value="active">Active</option><option value="draft">Draft</option><option value="archived">Archived</option></select><select className="form-select" value={categoryId} onChange={event => setCategoryId(event.target.value)}><option value="">All categories</option>{categories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></div><div className="glass-card table-container"><table className="data-table"><thead><tr><th>Product</th><th>Price</th><th>Stock</th><th>Status</th><th/></tr></thead><tbody>{visible.length === 0 ? <tr><td colSpan={5}>No products found.</td></tr> : visible.map(product => <tr key={product.id}><td><div className="product-cell">{product.thumbnail ? <img src={product.thumbnail} alt=""/> : <span className="image-fallback"/>}<span>{product.name}</span></div></td><td>{formatMoney(product.price,store?.currency??'PKR')}</td><td>{product.stock}</td><td><span className={`badge badge-${product.status === 'active' ? 'success' : 'muted'}`}>{product.status}</span></td><td className="actions"><Link className="btn btn-ghost btn-sm" href={`/admin/products/${product.id}`}>Edit</Link><button className="btn btn-danger btn-sm" onClick={async () => { if (confirm('Delete this product?')) { await fetch(`/api/admin/products/${product.id}`, { method: 'DELETE' }); void load(); } }}>Delete</button></td></tr>)}</tbody></table></div><Pagination page={page} pageCount={pageCount} onChange={setPage}/></>;
}
