'use client';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { BarChart3, Building2, LayoutDashboard, LogOut, Menu, Settings, Users, X, ClipboardList } from 'lucide-react';
import { useEffect, useState } from 'react';
import BrandMark from '@/components/ui/BrandMark';
const navItems = [{ href: '/super-admin', label: 'Dashboard', icon: LayoutDashboard, exact: true }, { href: '/super-admin/admins', label: 'Admins', icon: Users }, { href: '/super-admin/stores', label: 'Stores', icon: Building2 }, { href: '/super-admin/orders', label: 'All Orders', icon: ClipboardList }, { href: '/super-admin/analytics', label: 'Analytics', icon: BarChart3 }, { href: '/super-admin/settings', label: 'Settings', icon: Settings }];
export default function SuperAdminLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname(); const router = useRouter(); const [user, setUser] = useState<{ name: string; email: string } | null>(null); const [menuOpen, setMenuOpen] = useState(false);
  useEffect(() => { fetch('/api/auth/me').then(response => response.ok ? response.json() : null).then(data => setUser(data?.user ?? null)); }, []);
  const active = (href: string, exact?: boolean) => exact ? pathname === href : pathname.startsWith(href); if (pathname === '/super-admin/login') return <>{children}</>;
  return <div className="dashboard-layout">{menuOpen && <button className="sidebar-overlay" aria-label="Close navigation" onClick={() => setMenuOpen(false)}/>}<aside className={`sidebar ${menuOpen ? 'open' : ''}`}><Link href="/super-admin" className="sidebar-logo" onClick={() => setMenuOpen(false)}><BrandMark/><span><span className="sidebar-logo-text">ShopSaaS</span><span className="sidebar-logo-sub">Super Admin</span></span><button className="sidebar-close" type="button" onClick={event => { event.preventDefault(); setMenuOpen(false); }}><X size={18}/></button></Link><nav className="sidebar-nav"><div className="sidebar-section-label">Navigation</div>{navItems.map(item => { const Icon = item.icon; return <Link key={item.href} href={item.href} className={`sidebar-item ${active(item.href, item.exact) ? 'active' : ''}`} onClick={() => setMenuOpen(false)}><Icon size={18}/>{item.label}</Link>; })}</nav><div className="sidebar-footer">{user && <div className="sidebar-user"><div className="avatar">{user.name?.[0]?.toUpperCase()}</div><div>{user.name}<small>{user.email}</small></div></div>}<button onClick={async () => { await fetch('/api/auth/logout', { method: 'POST' }); router.push('/super-admin/login'); }} className="sidebar-item w-full danger-link"><LogOut size={18}/>Logout</button></div></aside><main className="main-content"><header className="dashboard-header"><button className="mobile-menu-btn" aria-label="Open navigation" onClick={() => setMenuOpen(true)}><Menu size={20}/></button><div className="dashboard-header-left"><div className="dashboard-header-title">{navItems.find(item => active(item.href, item.exact))?.label || 'Super Admin'}</div><div className="dashboard-header-sub">Platform management console</div></div><div className="dashboard-header-right"><span className="badge badge-info">Super Admin</span></div></header><div className="page-content">{children}</div></main></div>;
}
