'use client';
import { useEffect, useState } from 'react';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import { Building2, ClipboardList, Package, Users, WalletCards } from 'lucide-react';

const OrdersBarChart = dynamic(() => import('@/components/charts/OrdersBarChart'), { ssr: false, loading: () => <div className="chart-loading" /> });

type Stats = { totalAdmins: number; activeAdmins: number; totalStores: number; activeStores: number; totalProducts: number; ordersLast7Days: number; totalRevenue: number };
type Order = { id: string; orderNumber: string; total: number; status: string; createdAt: string; customer: { name: string } };
const statusColors: Record<string, string> = { pending: 'warning', confirmed: 'info', processing: 'info', shipped: 'accent', delivered: 'success', cancelled: 'error' };

export default function SuperAdminDashboard() {
  const [stats, setStats] = useState<Stats | null>(null); const [orders, setOrders] = useState<Order[]>([]);
  useEffect(() => { Promise.all([fetch('/api/super-admin/stats').then(response => response.json()), fetch('/api/super-admin/orders').then(response => response.json())]).then(([statsData, ordersData]) => { setStats(statsData); setOrders((ordersData.orders ?? []).slice(0, 8)); }); }, []);
  const chartData = Array.from({ length: 7 }, (_, index) => { const date = new Date(); date.setDate(date.getDate() - (6 - index)); return { day: date.toLocaleDateString('en-US', { weekday: 'short' }), orders: orders.filter(order => { const created = new Date(order.createdAt); return created.getDate() === date.getDate() && created.getMonth() === date.getMonth() && created.getFullYear() === date.getFullYear(); }).length }; });
  const cards = [[Users, 'Total admins', stats?.totalAdmins ?? 0, `${stats?.activeAdmins ?? 0} active`, 'accent'], [Building2, 'Total stores', stats?.totalStores ?? 0, `${stats?.activeStores ?? 0} active`, 'cyan'], [Package, 'Total products', stats?.totalProducts ?? 0, '', 'success'], [WalletCards, 'Platform revenue', `$${(stats?.totalRevenue ?? 0).toFixed(0)}`, `${stats?.ordersLast7Days ?? 0} orders this week`, 'warning']] as const;
  return <div><div className="page-header"><div><h1 className="page-title">Platform overview</h1><p className="page-subtitle">Your platform activity at a glance.</p></div><Link href="/super-admin/admins" className="btn btn-primary">Add admin</Link></div><div className="stat-grid">{cards.map(([Icon, label, value, detail, tone]) => <div className={`glass-card stat-card ${tone}`} key={label}><div className={`stat-icon ${tone}`}><Icon size={20}/></div><div className="stat-value">{value}</div><div className="stat-label">{label}</div>{detail && <div className="stat-change up">{detail}</div>}</div>)}</div><div className="dashboard-split"><div className="glass-card chart-card"><div className="chart-title">Orders this week</div><OrdersBarChart data={chartData}/></div><div className="glass-card quick-actions"><div className="chart-title">Quick actions</div>{[[Users, '/super-admin/admins', 'Manage admins', 'Create, suspend or edit platform access'], [Building2, '/super-admin/stores', 'View all stores', 'Monitor every active storefront'], [ClipboardList, '/super-admin/orders', 'All orders', 'Review activity across the platform']].map(([Icon, href, label, description]) => { const ActionIcon = Icon as typeof Users; return <Link key={href as string} href={href as string} className="quick-action"><span className="quick-action-icon"><ActionIcon size={18}/></span><span><strong>{label as string}</strong><small>{description as string}</small></span></Link>; })}</div></div><section className="glass-card recent-orders-card"><div className="section-heading"><h2>Recent orders</h2><Link href="/super-admin/orders" className="btn btn-ghost btn-sm">View all</Link></div><div className="table-container"><table className="data-table"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Status</th><th>Date</th></tr></thead><tbody>{orders.length === 0 ? <tr><td colSpan={5} className="table-empty">No orders yet</td></tr> : orders.map(order => <tr key={order.id}><td className="text-accent font-semibold">{order.orderNumber}</td><td>{order.customer?.name}</td><td className="font-semibold">${order.total.toFixed(2)}</td><td><span className={`badge badge-${statusColors[order.status] ?? 'muted'}`}>{order.status}</span></td><td>{new Date(order.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></div></section></div>;
}
