'use client';
import { useEffect, useState } from 'react';
type Discount = { id: string; code: string; type: 'percentage'|'fixed'; value: number; minOrderAmount: number; isActive: boolean; expiresAt?: string };
export default function DiscountsPage() {
  const [items, setItems] = useState<Discount[]>([]); const [error, setError] = useState(''); const [form, setForm] = useState({ code: '', type: 'percentage', value: '', minOrderAmount: '', expiresAt: '' });
  const load = () => fetch('/api/admin/discounts').then(response => response.json()).then(data => setItems(data.discounts ?? []));
  useEffect(() => { void load(); }, []);
  const create = async (event: React.FormEvent) => { event.preventDefault(); setError(''); const response = await fetch('/api/admin/discounts', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); if (!response.ok) { setError((await response.json()).error ?? 'Could not create coupon'); return; } setForm({ code: '', type: 'percentage', value: '', minOrderAmount: '', expiresAt: '' }); void load(); };
  return <><div className="page-header"><div><h1 className="page-title">Discounts</h1><p className="page-subtitle">Create coupon codes for your storefront.</p></div></div><form className="glass-card coupon-form" onSubmit={create}><input className="form-input" placeholder="Code e.g. WELCOME10" value={form.code} onChange={event => setForm({ ...form, code: event.target.value.toUpperCase() })} required/><select className="form-select" value={form.type} onChange={event => setForm({ ...form, type: event.target.value })}><option value="percentage">Percentage off</option><option value="fixed">Fixed amount off</option></select><input className="form-input" type="number" min="0.01" step="0.01" placeholder="Amount" value={form.value} onChange={event => setForm({ ...form, value: event.target.value })} required/><input className="form-input" type="number" min="0" step="0.01" placeholder="Minimum order (optional)" value={form.minOrderAmount} onChange={event => setForm({ ...form, minOrderAmount: event.target.value })}/><input className="form-input" type="date" value={form.expiresAt} onChange={event => setForm({ ...form, expiresAt: event.target.value })}/><button className="btn btn-primary">Create code</button>{error && <p className="form-error">{error}</p>}</form><div className="glass-card table-container"><table className="data-table"><thead><tr><th>Code</th><th>Discount</th><th>Minimum</th><th>Expires</th><th>Status</th><th/></tr></thead><tbody>{items.length === 0 ? <tr><td colSpan={6}>No coupon codes yet.</td></tr> : items.map(item => <tr key={item.id}><td className="font-semibold text-accent">{item.code}</td><td>{item.type === 'percentage' ? `${item.value}%` : `$${item.value.toFixed(2)}`}</td><td>${item.minOrderAmount.toFixed(2)}</td><td>{item.expiresAt ? new Date(item.expiresAt).toLocaleDateString() : 'Never'}</td><td><span className={`badge badge-${item.isActive ? 'success' : 'muted'}`}>{item.isActive ? 'active' : 'disabled'}</span></td><td className="actions"><button className="btn btn-ghost btn-sm" onClick={async () => { await fetch('/api/admin/discounts', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: item.id, isActive: !item.isActive }) }); void load(); }}>{item.isActive ? 'Disable' : 'Enable'}</button><button className="btn btn-danger btn-sm" onClick={async () => { if (confirm('Delete this coupon?')) { await fetch(`/api/admin/discounts?id=${item.id}`, { method: 'DELETE' }); void load(); } }}>Delete</button></td></tr>)}</tbody></table></div></>;
}
