'use client';
import { useEffect, useState } from 'react';
import { Search, SlidersHorizontal } from 'lucide-react';
import ProductCard from '@/components/store/ProductCard';
import Pagination from '@/components/ui/Pagination';
type Product = { id: string; name: string; price: number; comparePrice: number; thumbnail: string; images: string[]; discount: number; stock: number; variants: { name: string; options: string[]; priceModifier: number }[] }; type Category = { id: string; name: string };
export default function ProductsPage({ params }: { params: { storeSlug: string } }) {
  const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [search, setSearch] = useState(''); const [category, setCategory] = useState(''); const [sort, setSort] = useState('newest'); const [page, setPage] = useState(1); const perPage = 12;
  useEffect(() => { const controller = new AbortController(); const timer = window.setTimeout(() => { const query = new URLSearchParams({ search, sortBy: sort }); if (category) query.set('categoryId', category); fetch(`/api/store/${params.storeSlug}/products?${query}`, { signal: controller.signal }).then(response => response.json()).then(data => { setProducts(data.products ?? []); setCategories(data.categories ?? []); setPage(1); }).catch(error => { if (error.name !== 'AbortError') console.error(error); }); }, 180); return () => { controller.abort(); window.clearTimeout(timer); }; }, [params.storeSlug, search, category, sort]);
  const pageCount = Math.ceil(products.length / perPage); const visible = products.slice((page - 1) * perPage, page * perPage);
  return <main className="store-section"><div className="page-header catalog-heading"><div><p className="eyebrow">APPLE-COMPATIBLE ACCESSORIES</p><h1 className="page-title">Chargers, cables and more</h1><p className="page-subtitle">Find the right power accessory for your everyday setup.</p></div><span className="catalog-count">{products.length} product{products.length === 1 ? '' : 's'}</span></div><div className="catalog-filter"><div className="catalog-search"><Search size={18}/><input className="form-input" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search chargers and accessories"/></div><div className="catalog-filter-select"><SlidersHorizontal size={17}/><select className="form-select" value={category} onChange={event => setCategory(event.target.value)}><option value="">All categories</option>{categories.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></div><select className="form-select" value={sort} onChange={event => setSort(event.target.value)}><option value="newest">Newest arrivals</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option></select></div>{visible.length ? <><div className="products-grid">{visible.map(product => <ProductCard key={product.id} product={product} slug={params.storeSlug}/>)}</div><Pagination page={page} pageCount={pageCount} onChange={setPage}/></> : <div className="empty-state">No accessories match your search.</div>}</main>;
}
